Python 3.13.0 (tags/v3.13.0:60403a5, Oct  7 2024, 09:38:07) [MSC v.1941 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license()" for more information.
>>> print('hello world")
...       
SyntaxError: unterminated string literal (detected at line 1)
>>> print('hello world')
...       
hello world
>>> print("hello world")
...       
hello world
>>> age=15
...       
>>> age
...       
15
>>> person1,person2,person3="Poonam","Diya","Bharati"
...       
>>> person1
...       
'Poonam'
>>> person2
...       
'Diya'
>>> person3
...       
'Bharati'
