>>> print('hello world')
...       
hello world
>>> print("hello world")
...       
hello world
>>> age=15
...       
>>> age
...       
15
>>> person1,person2,person3="Poonam","Diya","Bharati"
...       
>>> person1
...       
'Poonam'
>>> person2
...       
'Diya'
>>> person3
...       
'Bharati'
